Add UPDATED_SOURCES_REPORTER configuration in JSON schema
nvuillam/mega-linter pull request #322
Opened 2021-02-09 15:15 UTC by JimmyTournemaine

Fixes #321 

## Proposed Changes

1. Fixing missing UPDATED_SOURCES_REPORTER and UPDATED_SOURCES_REPORTER_DIR from configuration JSON Schema

## Readiness Checklist

### Author/Contributor
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

2021-02-09 15:16 UTC, JimmyTournemaine commented
@nvuillam docs/CHANGELOG.md have been edited when I run the `build.sh` script.
I can revert it if needed ;)

2021-02-09 15:34 UTC, nvuillam commented
Its is updated only if there are new version of linters ^^
For manual update, please make sure you update the root changelog and not the one in docs folder :)

2021-02-09 16:14 UTC, JimmyTournemaine commented
Of course it is, I'm just dump (and I should open the file cause it seems that I don't know hot to read a git diff) :)

2021-02-09 18:53 UTC, nvuillam requested changes
Plz make updates requested in comments :)
About CI failing, it's not your fault, i'm working to solve that on master branch so your PR will pass once you merge master into your branch :)

2021-02-09 18:53 UTC, nvuillam commented on megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
> +      "title": "TYPESCRIPT_STANDARD: Activates/deactivates reporter",
Wrong title ^^

2021-02-09 18:53 UTC, nvuillam commented on megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
> +      "title": "TYPESCRIPT_STANDARD: Sub-folder of reports folder containing updated sources",
Wrong title ^^

2021-02-09 18:53 UTC, nvuillam commented on megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
> +      "title": "TYPESCRIPT_STANDARD: Activates/deactivates reporter",
plz set "Activates/Deactivated updated sources reporter"

2021-02-09 18:53 UTC, nvuillam commented on megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
> +      "title": "TYPESCRIPT_STANDARD: Sub-folder of reports folder containing updated sources",
juste remove the "TYPESCRIPT_STANDARD" :p

2021-02-09 20:28 UTC, JimmyTournemaine commented
so many mistakes... i have squashed my commits to hide my shame and taken into account your comments :)

2021-02-10 06:24 UTC, nvuillam requested changes
plz check the comment about the typo ^^

+ Please update CHANGELOG.md
then run `bash build.sh` :)

(cf [Contributing guide](https://nvuillam.github.io/mega-linter/contributing/))

2021-02-10 06:24 UTC, nvuillam commented on megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
> +      "title": "Activates/Deactivated updated sources reporter",
"Activates/Deactivates", plz ^^

2021-02-10 06:25 UTC, nvuillam commented
@JimmyTournemaine t'avais ptetre un peu trop forcé sur le chouchen, ou alors t'étais pas encore totalement redescendu depuis la Rave Party de Lieuron, ça arrive ;)

CI issues are solved in master, please merge master in your branch, fix the typo, update the changelog,  and it will all pass, make you a part of the Mega-Linter contributors Hall Of Fame 😃

2021-02-10 12:26 UTC, nvuillam approved these changes

2021-02-10 12:27 UTC, merged

2021-02-10 12:27 UTC, nvuillam commented
Thanks for your contribution ;)

Portsall forever !